<?php
// Autogenerated extension filesystems
// This config is merged with config/filesystems.php

return [
  'disks' => [
    /* blueprint/disks *//* TranslationsStart */ 'blueprint:translations' => [ 'driver' => 'local', 'root' => storage_path('extensions/translations'), 'url' => env('APP_URL') . '/fs/extensions/translations', 'visibility' => 'public', 'throw' => false, ], 'blueprint_private:translations' => [ 'driver' => 'local', 'root' => storage_path('.extensions/translations'), 'throw' => false, ], /* TranslationsEnd *//* PaneladdressoverrideStart */ 'blueprint:paneladdressoverride' => [ 'driver' => 'local', 'root' => storage_path('extensions/paneladdressoverride'), 'url' => env('APP_URL') . '/fs/extensions/paneladdressoverride', 'visibility' => 'public', 'throw' => false, ], 'blueprint_private:paneladdressoverride' => [ 'driver' => 'local', 'root' => storage_path('.extensions/paneladdressoverride'), 'throw' => false, ], /* PaneladdressoverrideEnd *//* DarkenateStart */ 'blueprint:darkenate' => [ 'driver' => 'local', 'root' => storage_path('extensions/darkenate'), 'url' => env('APP_URL') . '/fs/extensions/darkenate', 'visibility' => 'public', 'throw' => false, ], 'blueprint_private:darkenate' => [ 'driver' => 'local', 'root' => storage_path('.extensions/darkenate'), 'throw' => false, ], /* DarkenateEnd *//* ConsolelogsStart */ 'blueprint:consolelogs' => [ 'driver' => 'local', 'root' => storage_path('extensions/consolelogs'), 'url' => env('APP_URL') . '/fs/extensions/consolelogs', 'visibility' => 'public', 'throw' => false, ], 'blueprint_private:consolelogs' => [ 'driver' => 'local', 'root' => storage_path('.extensions/consolelogs'), 'throw' => false, ], /* ConsolelogsEnd */
  ],
];
